"""Backward-compatible aggregate of modular SQLAlchemy models."""

from app.modules.calculations.models import (
    AuditEvent,
    CalculationRun,
    CalculationSnapshot,
    CalculationStatus,
    EvidenceDocument,
    OutboxEvent,
    ResultContribution,
    ResultSummary,
)
from app.modules.catalog.models import (
    BomLine,
    EmissionFactor,
    EnergyActivity,
    Equipment,
    FactorVersion,
    MappingStatus,
    Material,
    MaterialProcessMapping,
    ModelTemplate,
    ModelTemplateVersion,
    ProcessRoute,
    Product,
    ProductVersion,
    RouteStep,
    Supplier,
    TransportActivity,
)
from app.modules.imports.models import ImportIssue, ImportJob, ImportStatus
from app.modules.model_base import TimestampMixin, new_id, utcnow

__all__ = [
    "AuditEvent",
    "BomLine",
    "CalculationRun",
    "CalculationSnapshot",
    "CalculationStatus",
    "EmissionFactor",
    "EnergyActivity",
    "Equipment",
    "EvidenceDocument",
    "FactorVersion",
    "ImportIssue",
    "ImportJob",
    "ImportStatus",
    "MappingStatus",
    "Material",
    "MaterialProcessMapping",
    "ModelTemplate",
    "ModelTemplateVersion",
    "OutboxEvent",
    "ProcessRoute",
    "Product",
    "ProductVersion",
    "ResultContribution",
    "ResultSummary",
    "RouteStep",
    "Supplier",
    "TimestampMixin",
    "TransportActivity",
    "new_id",
    "utcnow",
]
